# Generated by Django 6.0 on 2026-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('chandeliers', 'Chandeliers'), ('table lamps', 'Table Lamps'), ('floor lamps', 'Floor Lamps'), ('outdoor lamps', 'Outdoor Lamps'), ('pendant', 'Pendant'), ('wall lights', 'Wall Lights')], max_length=50)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
